tiktok:
  cookies_file: ''
polling:
  interval_minutes: 3
  delay_between_requests: 1
discord:
  bot_name: Aymannoti
dashboard:
  host: 0.0.0.0
  port: 8080
groups:
- name: ASL
  webhook_url: https://discord.com/api/webhooks/1480355912119095448/6kEbIrEF5UIZU5CjFzdMRGkAFcM70i58SRxJLYgBvk_DJP7Bxoq5GraTj9OSN3gZgWo_
  accounts:
  - callmeno_
  - .z5d_
  - 7il_8r
  - l580550
  - r_rs333
  - 1020.xf
  - etypolm901
  - li38k
  - daryn26_
  - abu7.6
  - 0jsih7
  - salish
  - ausui91
  - realoneefr
  - il7zni
  - xirlii4
  - hunacu
  - snii7l
  - sr7ct
  - thisnone7
  - nuilnt
  - lcu.s
  - 0sgj2
  - noni4671
  - liippe6
  - cry666castles
  - x8radx
  - 536l7
  - 7zikk
  - lo111n
  - z930161
  - 7_a979
  - llic67
  - ralv.9
  - tolydrafts
  - p73i7l1
  - imr7ii
  - xxxx4xxxx44
  - urdreamgirllx
  - r_e22r
  - nouserxxv
  - vlix23
  - ar_x1940
  - gfgifrhn8a3
  - r113154
  - .re_q
  - nnndex
  - nh2_00
  - usernamesama3
  - uyilldy
  - wessy_lf
  - jx1je7
  - 5uzyi
  - 2i.5l
  - lujaijrwmac
  - s.2kv
  - s__4ee
  - llooii87
  - abd111.2
  - jione.o0
  - qprvil
  - i7i.1l
  - bl89.n
  - to_lee17
  - nvninz
  - olilil053
  - catw0man6
  - 0yvn10
  - iaksslbky0q
  - l7lolly
  - iu3ov1
  - fkx_06
  - lllgg47
  - etherealliora
  - dn7ii1
  - wruia4
  - aannggelll_7
  - oillox0
  - rllio7
  - applio3
  - li94975
  - justtiredd9
  - 5rey.1
  - xiey_70
  - 2bi.xl
  - 4pelc2
  - riayllsi
  - karmapolicelvl99
  - pinkydidiii
  - meiiii.____
  - cyangelv
  - cooxxe00
  - jikjk0
  - .tna._
  - waard.2
  - karsthebestboy
  - mimavibe
  - rex7i1
  - sosssy9
  - liooiop
  - jjooj77
  - hyq965
  - yjy_il
  - l.u977
  - rrr.4666
  - r_hk99
  - alanaluise
  - ghlo0o0
  - liqr
  - llli_101
  - rinqwwo
  - cool_potato269
  - nevergttncloser
  - 8ie98
  - loly_ll7
  - 7ilrc1
  - iubv11
  - laura4good
  - bea_swag
  - vqp7l
  - 4ticer
  - 1ecv
  - ivguvtulqbv
  - lxluluz
  - r7rp
  - lostdody
  - pumkin.11
  - 669k96969996696
  - a7_0_7b
  - lil2vul
  - joojiiyy
  - 2iineo
  - q.aura1
  - rafeef_alsh2
  - s.2a.22
  - l4zurka
  - lcwe
  - uesr2000118
  - cveriox
  - mlllaaakkk
  - rrs.74
  - vixnt33
  - bessan_esmail
  - iiyj_o9
  - nn.77711
  - iio8lj7
  - aalles
  - oiuyyv
  - 5j.ajj
  - moonofstrawberry
  - loolitta21core
- name: asmk
  webhook_url: https://discord.com/api/webhooks/1480454309115068456/_o7yj49hYbcIgZtYX5j7Z9uoJqA2qM8Xz1J0HL7Wl-iNOCmGSpDTSYUz5TYnPUlKiYnY
  icon: "\U0001F3AE"
  accounts:
  - l.h.i77
  - nofixxxr
  - _37ds
  - ososkiuzgyx
  - lliiixna
  - ajo.507
  - jeje4.3
  - princesstotoy
  - ux.00i
  - o865759
  - eternalaura44
  - nini63_8
  - jood6791
  - celinaadla
  - lojain5852
  - m0m00.0
  - hfzjfxrabmg
  - justtsoso3
  - i.7mol
  - 069i1
  - 7nni3__
  - malaak1_8
  - ward_2023
  - 3.qii_
  - ee3xf
  - .scuce
  - chrriiy
  - jo0ona200
  - hopekillyou
  - blakaiyywhvavj
  - ketf
  - si9xq
  - ioi1242
  - lenamhlhl
  - goneallready
  - saba_v73
  - ret302a
  - 2in.s
  - oio.00o1
  - 7iiox__
  - g2hll
  - gmrek
  - rblil
  - dont.follow.me020
  - justnaya_8
  - angel1_677
  - xxi.h2
  - eeiyl
  - mrsackermaaan
  - redbull
- name: Tree server
  webhook_url: https://discord.com/api/webhooks/1480455404705026103/RuvtRkicTbFa-YERBUxyMFOA02rKY2ytsAvBDLQS_ZhwbgvNFe81phfTId_h8kHS8mFz
  icon: "\U0001F525"
  accounts:
  - 123654lll3
  - lolyc297
  - maleka.707
  - 3got0
  - vviimmll
  - qlxzn2
  - youngforeve4r
  - kw.z020
  - becuffuak
  - non81488
  - f.ert122
  - ilwvr1
  - 7eie
  - b01c_
  - oqix10
  - blavvk4
  - mlka13.d
  - lxm7_ll
  - faiijl5
  - rrllov
  - lmluv.x
  - wwir6
  - wug04
  - 0jjioi
  - saraniumm
  - ijuryx
  - nottery1
  - 66.tik
  - xi8il1
  - zscil
  - ineedbraeth
  - oooll.44
  - ydjsnm
  - leauemeal0ne
  - nona_almalik
  - gppp901
  - seraphicarua
  - yuynyny
  - joury.alshehri
  - jwana6126.1
  - 66oer_
  - breee.ia
  - lno402
  - sh_r5x
  - il7olil
  - cvrhiagncea
  - malkbukhary
  - rand_alsh
  - riloo_6
  - zto46z
  - alinka_16_ag
  - _4rtjl
  - 15ltr
  - thebiiigthreee
  - lliiicv
  - useriif
  - merdour
  - inursea
  - ixl.n0
  - 56li56
  - rema_637
  - it6ara
  - .v39oq
  - _tvvd
  - life.l8
  - rem14j
  - .6lwe
  - yas_701_
  - suzzus7
  - goldenipadbaddie
  - jj2r3
  - peounq
  - eseahfaha.d1
  - jwana6126
  - itssayla1
  - syhyu
  - sos.577
  - 2ott.a
  - iucola
  - ririoow
  - dodo14503
  - cai2i
  - sozy1829
  - 5lnlw
  - pearlltey
  - s.485a
  - dode20241
  - dlooly2
  - daar_6
  - iovveer
  - t.7ril
  - d12_331
  - angel_777i
  - dl3.b
  - jo.h39
  - nucitakawai
  - j_xxx.6
  - mimi13rrr7
  - e9.rb
  - aiiui7
  - hjkk666_
  - il.o555
  - hiren
  - queennroryy
  - nony.aogaifi
  - pjllny
  - ahf546
  - uiecsa1
  - j71s7
  - ii7r13
  - uiwdr
  - xiil2r_
  - sr__5681
  - maylz4
  - lulo.ii3
  - youuu1d
  - nj.mariom
  - exir707
  - cloudkissie
  - it5wp
  - 0ilzqu
  - 1css6
  - uioll707
  - a1sjl
  - loly37508
  - hqiwjwj5
- name: speedlo-2
  webhook_url: https://discord.com/api/webhooks/1482814149296783412/R2y92WV3LkOG451Vg22WvrCMIBqzT6uM60bb93o4EdoVlhg9wQHGbWSFOUY4_jtK6JLx
  icon: "\U0001F525"
  accounts:
  - dan.evan42
  - al1anoud1
  - syiriyesiteatieautea506
  - e1r.n2
  - cvqxi3
  - _mariam_maged
  - r.ov1i
  - r_ilr49
  - 911.iilx0
  - wliio5_
  - luvleyxaa
  - n3038469
  - s0137187
  - notmeanymorebaby
  - ftnac12
  - 7rb.lilll
  - crunchyuni
  - .1lix455
  - tot.alagg
  - iiqooii
  - ev17176
  - r_9r_
  - jbnd3
  - ril1q
  - xriich_
  - tint752
  - meme82516
  - notasaharprise_
  - roryangel88
  - 7lloi9
  - fiil.6
  - c9vln
  - skltkamk
  - wcj9
  - at_1lj
  - naxji
  - cvlvt
  - uiillii5
  - 6blj2
  - qvh.60
  - t3.9d2
  - .x.5156
  - _llii98
  - xcsd515
  - xmxa26
  - i.we14
  - ttuuuiiiiiii
  - knl070
  - o2uiifl_
  - unknownqp07
  - llliiioonn
  - angelgirl1ii
  - loostinyouu
  - gomaleusfura
  - .iiv_0
  - lz2rz
  - babygrrx
  - la.50q
  - calllmebunbun
  - ushcvseqclw
  - nooonny505
  - j_a_na18
  - salohxekn5y
  - greenlamborrghini
  - 7iizz_6
  - privaterrroro
  - a_.tll
  - user.726472838192
  - um_naif73
  - ev0oz
  - iiliooxa
  - lllweeo
  - sosin___1
  - icantmoveon4
  - 17a_a7
  - totoax1
  - bsaket3
  - nc7m2
  - cllpoiz
  - 402rae
  - zwmfcc11
  - 4llioq
  - ziil77
  - pi2v0
  - kfvjj1
  - vilnten
  - da7n.0
  - oxbid
  - xiicl4
  - hebah.media
  - n.foiu
  - yory702_
  - user1038395379
  - gogo_6688.8
  - ms_jeem3
  - s7915211
  - norahhia
  - ol505
  - r.liim7
  - am_ioi5
  - wtr0j
  - ..me0141
  - pd0i
  - queensssoso
  - rooorreey
  - ged..0
  - rcen.0
  - jourijojojo
  - sa.dana.ae
  - lovelllyety
  - w0n703
  - .srn.1
  - fode_30
  - poyes55
  - l0didi
  - wy2ril
  - sghsheyehehs
  - liiaq4
  - ealio1
  - huon761
  - mill4rayy
  - r2kf
  - 0xir8_
  - jdissnbz3jjnskskskskksk1
  - rrewli
  - xon_127
  - r.7aa7
  - _iharley
  - gto1.2
  - carrotll00
  - _dixi8
  - k2231655
  - marwasu_
  - jvqi0
  - rilla951
  - le8.lee
  - s0775563
  - fccx.o
  - stanaci
  - iamgmr2
  - 6cff1
  - m_1m1mr
  - meow.vk1
  - rrs.20
  - beautiffulll
  - _aamarr
  - nnooottr
  - _r.rkj_
  - xoxomsjojo
  - paulinita.0
  - xlgk73
  - ilklq0
  - dinlrq
  - kalalalalaaiala
  - wilr0_
  - lucy40532
  - __0wgj
  - asoly67
  - cr.lx0
  - wuc7v
  - meownoud
  - laquree
  - s_sar02
  - 3blyl
  - ilmsjo
  - rv.132
  - zoom701111
  - princbun
  - se_la10
  - 7lade_
  - naw_af.10
  - tfsvl
  - qviq_
  - i_ils11
  - rinad___0
  - txsl5
  - lig4i
  - 2yliy7
  - iji.ix
  - 1.cancerr
  - s.h19995
  - i0obj
  - xshxnwi
  - xj.2s
  - 5liuss
  - dangerousi0
  - albgaa1
- name: speedlo07
  webhook_url: https://discord.com/api/webhooks/1480328576371920997/maLkLj79_boNuHxfl6FHGEfU2P9GVVwBj78wkWoD7IeStoBard46Cx0CBK-syYNGbvXW
  icon: "\U0001F451"
  accounts:
  - ji_177u
  - mayar.xp3
  - srhanalshri
  - nooooooonnnnee
  - oxi7.7
  - vershyninaliza1
  - l4.on2
  - holyfvckihu
  - meiroksa5
  - bayan2599
  - aiivvs1_
  - vcill47
  - _anotherlevel1
  - loly30956
  - jo_j70
  - ctrfybn
  - lilisr_sa
  - jji_l3
  - pr3_h1
  - r302500
  - rodina_ahmad6
  - loli0.4
  - hpvm5
  - ja00174
  - aaaa29904
  - velvii99
  - 8uiw1
  - m.xoil3
  - t76u
  - sara_saad29
  - ju36z
  - veryypretty
  - kh_iii6
  - enndiaries
  - s9036626
  - layan40181
  - y3zj
  - sorrowfuuull
  - ssaat72
  - xoxo_ll00
  - memeanglll
  - ncii0l
  - rma_087
  - yaud1097d6t
  - qwau.9
  - n1ssll_
  - xt.uh4
  - etticter
  - ew.xj
  - maybesew1fs
  - iiioo291
  - ghnoonaa
  - t50r2
  - sc.uii
  - 7777.7777._77
  - zv_lix
  - userr07070707007
  - octlost
  - si.0704
  - onl273
  - lknir3
  - awsk_2
  - prretttywoman
  - emispellbook
  - lujain.al.saif
  - jiin.4
  - imhysm
  - rkjli
  - le8ji
  - d10al_
  - 6.wd20
  - leen.0_0
  - plkjle
  - i.l.q_
  - emilylaur
  - ert_iv
  - dodykissme
  - rxil7iv
  - xxian70
  - jijiz.120
  - emptyrory
  - sii_561
  - qqail1
  - raidbk1
  - ln.78k
  - '2._19'
  - noturoreoo
  - ch.r90
  - 8xxc15
  - 0iiidddkkk1
  - m3558623
  - amgattara
  - iilnlly
  - je.je9200
  - 0jno
  - shhshqxhwcq
  - x50_3
  - vwkd
  - vle.n
  - 8eii.n
  - 8u.777
  - erx_ll
  - qlev_
  - zz3hd1
  - worldswhite
  - nonys7
  - you__913
  - user2710799275162
  - suuqii
  - .v1rl
  - loly.7007
  - u.o246
  - mayyyarrri21
  - sarakrmh
  - alinaaintcarin
  - p.w7q
  - paulina.mtzz2
  - 8exq5
  - .eipt
  - i9jki
  - vlln.1
  - qqi1o
  - l2hei
  - lou99x
  - unheu
  - l8rlj
  - 503.ps
  - realbayan
  - xoxo_reham
  - 1dhla
  - heellokittyy0
  - ivfxt
  - renxrrx
  - wwaax18
  - 2mail76
  - .7ii91
  - prettysaudigirl
  - by.sahaab
  - oill_27
  - _9x02
